

-- rytvuV8!@

headers = [
"UNIQUE_KEY",
"PRODUCT_TITLE",
"PRODUCT_DESCRIPTION",
"SANMAR_MAINFRAME_COLOR",
"SIZE",
"COLOR_NAME",
"PIECE_PRICE"
]

CREATE TABLE IF NOT EXISTS file_data (
        UNIQUE_KEY INT PRIMARY KEY,
        PRODUCT_TITLE TEXT,
        PRODUCT_DESCRIPTION TEXT,
        SANMAR_MAINFRAME_COLOR TEXT,
        SIZE TEXT,
        COLOR_NAME TEXT,
        PIECE_PRICe REAL
)


INSERT INTO file_data (UNIQUE_KEY, PRODUCT_TITLE, PRODUCT_DESCRIPTION, SANMAR_MAINFRAME_COLOR, SIZE, COLOR_NAME, PIECE_PRICE)
VALUES (value1, value2, ...)
ON CONFLICT (UNIQUE_KEY) DO UPDATE SET
        PRODUCT_TITLE = excluded.PRODUCT_TITLE,
        PRODUCT_DESCRIPTION = excluded.PRODUCT_DESCRIPTION,
        SANMAR_MAINFRAME_COLOR = excluded.SANMAR_MAINFRAME_COLOR,
        SIZE = excluded.SIZE,
        PIECE_PRICE = excluded.PIECE_PRICE,
        WHERE 
        file_data.PRODUCT_TITLE != excluded.PRODUCT_TITLE OR
        file_data.PRODUCT_DESCRIPTION != excluded.PRODUCT_DESCRIPTION OR
        file_dataSANMAR_MAINFRAME_COLOR != excluded.SANMAR_MAINFRAME_COLOR OR
        file_data.SIZE != excluded.SIZE OR
        file_data.PIECE_PRICE 1= excluded.PIECE_PRICE
        ;